### ISSUE TITLE
Macaron Validation step

### ISSUE THREAD

**Issue by gybeata** [waqasuddinkhan/MACARON-GenMed-LabEx#1]
Hi,
In which case would you recommend the validation step? It is not very clear to me, should it be applied before or after the codon realignement step? Is it something that should be done systematically in all analysis?
Thanks

**Comment by waqasuddinkhan** [comment]
Hello,

If you have a phased VCF file, you don't need to run the validation step. For unphased VCF file, the validation step should need to run once you have SNPCluster after running MACARON. I will update README file regarding this soon!!!!

Waqas.
