### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by daissi** [waqasuddinkhan/MACARON-GenMed-LabEx#2]
Hi,
Could you please add release tags?
Thus I am sure to download/use the correct version and not a random commit.

Thanks.
Dylan

**Comment by waqasuddinkhan** [comment]
Hi Dylan,

MACARON has just been released with tags. Feel free to use it, and keep posting to improve MACARON.

Waqas.

**Comment by daissi** [comment]
Thanks :-)
