### ISSUE TITLE
Change_zygo function fails

### ISSUE THREAD

**Issue by haiderinam** [waqasuddinkhan/MACARON-GenMed-LabEx#5]
MACARON seems to fail when there are two alt alleles at a single position. For example, at chr9 pos 1380000, REF is C and alt is A,T. The code fails on this line. The traceback I'm getting is:

**Generating a SnpCluster Table: Done!
Traceback (most recent call last):
  File "../MACARON", line 602, in <module>
    Search_CODON(INF, TMPDIR, GATK, SNPEFF, SNPEFF_HG, JAVA_OPTIONS, FIELDS, GATK4_alt)
  File "../MACARON", line 271, in Search_CODON
    chgz = Change_zygo(ref, alt, zyg)
  File "../MACARON", line 231, in Change_zygo
    print(csp[1])
IndexError: list index out of range**

The demo vcf provided in the github repo doesn't throw any errors but my vcf does. I'm pretty sure this is happening because of the two ALT alleles issue.

I have attached the .vcf. It uses GChr38.99
[NVC_Output.txt](https://github.com/waqasuddinkhan/MACARON-GenMed-LabEx/files/7262085/NVC_Output.txt)

I changed the name from NVC_Output.vcf to NVC_Output.txt because Github does not allow .vcf file format

Thanks for looking into this!
@waqasuddinkhan

**Comment by FlorianThibord** [comment]
Hi @haiderinam ,
Yep that's probably the case, MACARON does not handle multi-allelic vcf. You can try to split your multi-allelic positions into bi-allelic variants, for instance with bcftools:
`bcftools norm -m any input.vcf -o output.normalized.vcf -Ov`

**Comment by haiderinam** [comment]
Hi @FlorianThibord 
Thanks for the suggestion. I changed multi-allelic variants over to bi-allelic variants with bcftools norm. But I'm still getting an index out of bounds error.
`python ../MACARON -i nvc_snps_nomultiallelic_noNs.vcf`

`Generating a SnpCluster Table: Done!`            
`Traceback (most recent call last):
  File "../MACARON", line 601, in <module>`
    `Search_CODON(INF, TMPDIR, GATK, SNPEFF, SNPEFF_HG, JAVA_OPTIONS, FIELDS, GATK4_alt)`
  `File "../MACARON", line 270, in Search_CODON`
    `chgz = Change_zygo(ref, alt, zyg)`
  `File "../MACARON", line 235, in Change_zygo`
    `elif ((ref != csp[0]) and (ref == csp[1]) and ((csp[0] != ".") and (csp[1] != "."))):
IndexError: list index out of range`
`
Here's the vcf:
[nvc_snps_nomultiallelic_noNs.txt](https://github.com/waqasuddinkhan/MACARON-GenMed-LabEx/files/7267367/nvc_snps_nomultiallelic_noNs.txt)

**Comment by waqasuddinkhan** [comment]
There might be several reasons why MACARON is not working:

1. Multiallelic (solved by Florian), but still:
2. VCF file is not annotated
3. Your earlier VCF file is bit strange, continous stretch of genomic coordinates, even if we assume this all as bialleleic this is never ever possible in genomics data that you have continous SNPs. What's the source of data? Such adjacent SNPs hinders with the molecular biology concepts of annotation at protein levels too (exons and intorns).

**Comment by FlorianThibord** [comment]
Ok, the error was not thrown because of the multi-variant format (but it would have caused problems here as well). 
The reason behind this error is that the GT field does not correspond to a diploid genotype: the GT field should look like `0/1` for a heterozygous variant in an unphased vcf or `0|1` for a phased vcf. In your case, you only have `0` or `1` in that field which corresponds to a haploid genotype. 
In the `change_zygo` function, we split the GT string on either `/` or `|`, and store the values in `csp`. Since the separator is absent for haploid genotypes, csp only contains 1 element, and python throws an error when trying to access the 2nd element.
Unfortunately, MACARON only works with diploid genotypes at this point. 
Let me know if you need additional information.

**Comment by haiderinam** [comment]
Thank you Florian. That makes sense. The GT field for a non-diploid GT would not be 0|1 or 0/1. And hence would throw errors in the change_zygo function

The VCF file had a lot of variants because it was an NNK saturating mutagenesis library with ~5k unique variants. Variants in NNK libraries are ~50% MNVs. I was having a tough time variant calling for MNVs with other variant callers so I thought I would give this software a shot. e.g. Naive Variant Caller detected a lot of SNPs but no MNVs. Unfortunately for MACARON, these MNVs are also multi-allelic. So I can't use the software to correct the 'SNPs' that NVC is calling.

Thank you for looking into this error for me.

**Comment by FlorianThibord** [comment]
I was trying to find a fix for this, but it would be a bit too complex to rewrite MACARON for different ploidy. 

One thing you could try is slightly modifying your VCF to simulate a diploid, where the second allele is always the reference allele: when you have `1` or `0` in the `GT` field, you can change it to `1/0` or `0/0,` respectively. MACARON should be able to work with it, but it will give you the results for all the combinations, so it would be up to you to remove the combinations involving the simulated reference allele.
